config/routes.rb
Rails.application.routes.draw do
  resources :aktivni_pojistenis
  resources :pojistenecs
  resources :pojistenis
  #get 'home/index'
  root 'home#index'
  get 'home/info'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/aktivni_pojisteni.rb
class AktivniPojisteni < ApplicationRecord
  belongs_to :pojistenec
  belongs_to :pojisteni
  validates :castka, presence: { message: "musí být vyplněna" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pojistenec.rb
class Pojistenec < ApplicationRecord
	has_many :aktivni_pojistenis, dependent: :destroy
	has_many :pojistenis, through: :aktivni_pojistenis, dependent: :destroy
	validates :jmeno, length: { minimum: 2 }
	validates :prijmeni, length: { minimum: 2 }
	validates :telefon, uniqueness: true
end

app/models/pojisteni.rb
class Pojisteni < ApplicationRecord
	has_many :aktivni_pojistenis, dependent: :destroy
	has_many :pojistenecs, through: :aktivni_pojistenis, dependent: :destroy
	validates :nazev, uniqueness: true
end

app/controllers/aktivni_pojistenis_controller.rb
class AktivniPojistenisController < ApplicationController
  before_action :set_aktivni_pojisteni, only: %i[ show edit update destroy ]

  # GET /aktivni_pojistenis or /aktivni_pojistenis.json
  def index
    @aktivni_pojistenis = AktivniPojisteni.all
  end

  # GET /aktivni_pojistenis/1 or /aktivni_pojistenis/1.json
  def show
  end

  # GET /aktivni_pojistenis/new
  def new
    @aktivni_pojisteni = AktivniPojisteni.new
  end

  # GET /aktivni_pojistenis/1/edit
  def edit
  end

  # POST /aktivni_pojistenis or /aktivni_pojistenis.json
  def create
    @aktivni_pojisteni = AktivniPojisteni.new(aktivni_pojisteni_params)

    respond_to do |format|
      if @aktivni_pojisteni.save
        format.html { redirect_to aktivni_pojisteni_url(@aktivni_pojisteni), notice: "Aktivni pojisteni was successfully created." }
        format.json { render :show, status: :created, location: @aktivni_pojisteni }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aktivni_pojisteni.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aktivni_pojistenis/1 or /aktivni_pojistenis/1.json
  def update
    respond_to do |format|
      if @aktivni_pojisteni.update(aktivni_pojisteni_params)
        format.html { redirect_to aktivni_pojisteni_url(@aktivni_pojisteni), notice: "Aktivni pojisteni was successfully updated." }
        format.json { render :show, status: :ok, location: @aktivni_pojisteni }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aktivni_pojisteni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aktivni_pojistenis/1 or /aktivni_pojistenis/1.json
  def destroy
    @aktivni_pojisteni.destroy

    respond_to do |format|
      format.html { redirect_to aktivni_pojistenis_url, notice: "Aktivni pojisteni was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aktivni_pojisteni
      @aktivni_pojisteni = AktivniPojisteni.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aktivni_pojisteni_params
      params.require(:aktivni_pojisteni).permit(:pojistenec_id, :pojisteni_id, :castka)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def info
  end
  
end

app/controllers/pojistenecs_controller.rb
class PojistenecsController < ApplicationController
  before_action :set_pojistenec, only: %i[ show edit update destroy ]

  # GET /pojistenecs or /pojistenecs.json
  def index
    @pojistenecs = Pojistenec.all
  end

  # GET /pojistenecs/1 or /pojistenecs/1.json
  def show
  end

  # GET /pojistenecs/new
  def new
    @pojistenec = Pojistenec.new
  end

  # GET /pojistenecs/1/edit
  def edit
  end

  # POST /pojistenecs or /pojistenecs.json
  def create
    @pojistenec = Pojistenec.new(pojistenec_params)

    respond_to do |format|
      if @pojistenec.save
        format.html { redirect_to pojistenec_url(@pojistenec), notice: "Pojistenec was successfully created." }
        format.json { render :show, status: :created, location: @pojistenec }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pojistenec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pojistenecs/1 or /pojistenecs/1.json
  def update
    respond_to do |format|
      if @pojistenec.update(pojistenec_params)
        format.html { redirect_to pojistenec_url(@pojistenec), notice: "Pojistenec was successfully updated." }
        format.json { render :show, status: :ok, location: @pojistenec }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pojistenec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pojistenecs/1 or /pojistenecs/1.json
  def destroy
    @pojistenec.destroy

    respond_to do |format|
      format.html { redirect_to pojistenecs_url, notice: "Pojistenec was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pojistenec
      @pojistenec = Pojistenec.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pojistenec_params
      params.require(:pojistenec).permit(:jmeno, :prijmeni, :datum_narozeni, :telefon, :email, :ulice, :mesto)
    end
end

app/controllers/pojistenis_controller.rb
class PojistenisController < ApplicationController
  before_action :set_pojisteni, only: %i[ show edit update destroy ]

  # GET /pojistenis or /pojistenis.json
  def index
    @pojistenis = Pojisteni.all
  end

  # GET /pojistenis/1 or /pojistenis/1.json
  def show
  end

  # GET /pojistenis/new
  def new
    @pojisteni = Pojisteni.new
  end

  # GET /pojistenis/1/edit
  def edit
  end

  # POST /pojistenis or /pojistenis.json
  def create
    @pojisteni = Pojisteni.new(pojisteni_params)

    respond_to do |format|
      if @pojisteni.save
        format.html { redirect_to pojisteni_url(@pojisteni), notice: "Pojisteni was successfully created." }
        format.json { render :show, status: :created, location: @pojisteni }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pojisteni.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pojistenis/1 or /pojistenis/1.json
  def update
    respond_to do |format|
      if @pojisteni.update(pojisteni_params)
        format.html { redirect_to pojisteni_url(@pojisteni), notice: "Pojisteni was successfully updated." }
        format.json { render :show, status: :ok, location: @pojisteni }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pojisteni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pojistenis/1 or /pojistenis/1.json
  def destroy
    @pojisteni.destroy

    respond_to do |format|
      format.html { redirect_to pojistenis_url, notice: "Pojisteni was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pojisteni
      @pojisteni = Pojisteni.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pojisteni_params
      params.require(:pojisteni).permit(:nazev)
    end
end

app/helpers/aktivni_pojistenis_helper.rb
module AktivniPojistenisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pojistenecs_helper.rb
module PojistenecsHelper
end

app/helpers/pojistenis_helper.rb
module PojistenisHelper
end

app/views/aktivni_pojistenis/_aktivni_pojisteni.html.erb
<header>

  <h1>Detail pojištění</h1>

</header>

<section>

  <div id="box">

    <%= link_to "Upravit", edit_aktivni_pojisteni_path(aktivni_pojisteni), class:"button", id:"zeleny" %>

    <%= button_to "Smazat", aktivni_pojisteni, method: :delete, class:"button", id:"cerveny" %>

    <br>

  </div>

  <table id="info">
      
    <tr>
        
      <td>ID Pojištěnce:</td>
      <td><%= aktivni_pojisteni.pojistenec_id %></td>

    </tr>

    <tr>

      <td>ID Pojištění:</td>
      <td><%= aktivni_pojisteni.pojisteni_id %></td>
        
    </tr>

    <tr>

      <td>Měsíční částka v KČ:</td>
      <td><%= aktivni_pojisteni.castka %></td>

    </tr>
      
  </table>

</section>

app/views/aktivni_pojistenis/_form.html.erb
<%= form_with(model: aktivni_pojisteni) do |form| %>
  <% if aktivni_pojisteni.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aktivni_pojisteni.errors.count, "error") %> prohibited this aktivni_pojisteni from being saved:</h2>

      <ul>
        <% aktivni_pojisteni.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :"Pojištěnec", style: "display: block" %>
    <%= form.select :pojistenec_id, Pojistenec.all.pluck(:id) %>
  </div>

  <div>
    <%= form.label :"Pojištění", style: "display: block" %>
    <%= form.select :pojisteni_id, Pojisteni.all.pluck(:id) %>
  </div>

  <div>
    <%= form.label :"Měsíční částka v Kč", style: "display: block" %>
    <%= form.number_field :castka %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/aktivni_pojistenis/edit.html.erb
<article>

  <h1>Úprava Pojištění</h1>

  <%= render "form", aktivni_pojisteni: @aktivni_pojisteni %>

  <br>

  <div>
    <%= link_to "Otevřít záznam", @aktivni_pojisteni, class:"button", id:"zeleny" %>

    <%= link_to "K pojištění", aktivni_pojistenis_path, class:"button", id:"zeleny" %>
  </div>
  
</article>

app/views/aktivni_pojistenis/index.html.erb
<article>

  <p style="color: green"><%= notice %></p>

  <header>
  
    <h1>Pojištění</h1>
  
    <div id="box">
      <%= link_to "Nové Pojištění", new_aktivni_pojisteni_path, class: "button", id:"zeleny" %>
      <%= link_to "Seznam pojistění", pojistenis_path, class:"button", id:"zeleny" %>
    </div>
  
  </header>
  
  <section>
  
    <table>

      <thead>

        <th>Pojištěný</th>

        <th>Pojištění</th>
        
        <th>Měsíční částka v kč</th></td>
        
        <th>Akce</th>
      
      </thead>
  
      <tbody>

        <% @aktivni_pojistenis.each do |aktivni_pojisteni| %>

        <tr>

          <td><%= aktivni_pojisteni.pojistenec_id %></td>

          <td><%= aktivni_pojisteni.pojisteni_id %></td>

          <td><%= aktivni_pojisteni.castka %></td>

          <td>
            <div id="box">
            <%= link_to "Zobrazit", aktivni_pojisteni, class:"button", id:"zeleny" %> 
            <%= link_to "Upravit", edit_aktivni_pojisteni_path(aktivni_pojisteni), class:"button", id:"zeleny" %> 
            <%=link_to "Smazat", aktivni_pojisteni, method: :delete, data: { confirm: 'Opravdu chtete smazat tento záznam?' }, class:"button", id:"cerveny" %>
            </div>
          </td>
        </tr>

        <% end %>

      </tbody>

    </table>

  </section>

</article>

app/views/aktivni_pojistenis/new.html.erb
<article>

  <h1>Nové pojištění</h1>

  <%= render "form", aktivni_pojisteni: @aktivni_pojisteni %>

  <br>

  <div>
    <%= link_to "Zpět", aktivni_pojistenis_path, class:"button", id:"zeleny" %>
  </div>

</article>

app/views/aktivni_pojistenis/show.html.erb
<article>
  <p style="color: green"><%= notice %></p>

  <%= render @aktivni_pojisteni %>

  <div id="box">

    <%= link_to "K pojištěním", aktivni_pojistenis_path, class:"button", id:"zeleny" %>

  </div>
</article>

app/views/home/_header.html.erb
<nav>

  <%= link_to 'Evidence', root_path, class:"logo" %>
  
  <ul>
  
    <li><%= link_to'Pojištěnci', pojistenecs_path %></li>

    <li><%= link_to 'Pojištění', aktivni_pojistenis_path %></li>

    <li><%= link_to 'O Aplikaci', home_info_path %></li>

  </ul>

</nav>

app/views/home/index.html.erb
<article>
	<header>
		<p>Vítejte v aplikaci evidence.</p>
		<h1>Novinky</h1>
	</header>
	<section>
		<h3>Novinka 1</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam quos ipsa expedita dicta? Quibusdam cum veniam nemo repellendus, debitis odit maiores quisquam, vero nulla culpa corporis nobis repellat minus! Dolores. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est laboriosam cumque, aliquid facilis accusantium saepe consequuntur. Eum adipisci accusamus illo iusto odit deleniti quasi est maxime, omnis in quam fuga! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam totam non incidunt voluptatem repudiandae vel minima ipsam ipsa, sequi ab voluptatibus id placeat nobis doloremque nisi, architecto, quia sunt veniam.</p>
	</section>
	<section >
		<h3>Novinka 2</h3>
		<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam maiores asperiores quidem eveniet fuga consectetur tenetur exercitationem nesciunt, totam facilis pariatur reprehenderit modi at voluptatum nobis ea autem? Est, nihil. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates asperiores, illum sunt veniam similique rem laborum error sed, eligendi atque officiis quidem itaque. Amet, neque delectus commodi laudantium a minus! <br>
		Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat architecto nesciunt, expedita molestiae, quis officiis rem distinctio cupiditate voluptatum, tempora temporibus repudiandae? Ab tenetur consequatur fugit debitis, voluptatum et atque? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates doloremque nobis illum architecto obcaecati dolores repellat reprehenderit veritatis repellendus soluta, necessitatibus, cumque optio ea itaque maxime. Placeat saepe a hic!</p>
	</section>
	<section>
		<h3>Novinka 3</h3>
		<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nobis reiciendis quas aliquam? Hic nobis sapiente voluptatibus ipsam quae facilis nihil sint ab recusandae. Ipsa modi rerum porro magni consectetur.</p>
		<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Esse molestias laborum sed, nesciunt accusantium magni animi, vitae eius culpa obcaecati voluptate accusamus laboriosam facilis eligendi quae nisi quam, tempora explicabo. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et ipsum corporis doloribus officia sunt ad quisquam repellat aliquam architecto eligendi tempore fuga, est dolores? Ullam corporis culpa explicabo dolor nobis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores, voluptatum eius ducimus laborum illum laudantium adipisci sequi commodi libero provident, odio beatae cum quasi sunt explicabo saepe ab voluptatem! Est?</p>
		<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni minima deleniti voluptates animi expedita. Deserunt, totam corrupti eaque nihil ex nostrum consectetur ipsa cum dolorum, pariatur dolor consequatur exercitationem minima. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ea sed necessitatibus, obcaecati mollitia nobis distinctio illo temporibus quam, dolor at provident fugiat alias voluptatum sit, ab maiores inventore corporis!</p>
	</section>
	<section>
		<h3>Novinka 4</h3>
		<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore, possimus. Tempore nihil fuga velit voluptatem, commodi accusantium corporis ducimus ut in eaque laborum magni minus maxime delectus itaque blanditiis error?Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur vero nostrum sint ut delectus nisi perspiciatis unde aliquid doloribus! Dolorum, sint tenetur! Pariatur necessitatibus in non cum ullam dolore omnis?<br>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae architecto rerum quaerat enim ducimus impedit quisquam, ipsum tenetur, sit veritatis reiciendis aliquid harum id hic magnam. Minima nemo ipsam iusto.</p>
		<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta et dolor eaque perspiciatis excepturi, facilis, minus ea adipisci officia porro libero. Vitae ab sit quos sapiente, a maxime velit architecto? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quisquam tenetur ratione minus molestiae. Cum animi culpa illum quia aut, esse amet dolorem voluptatibus. Est deserunt beatae quidem repellendus ad laboriosam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam dicta veniam nam repudiandae, cumque voluptate vel tenetur temporibus ratione asperiores, perspiciatis unde eius explicabo saepe? Aperiam exercitationem maiores soluta sit.</p>
	</section>
</article>

app/views/home/info.html.erb
<article>
    <header>
        <h3>O aplikaci</h3>
    </header>
    <section>
        <p>Verze: 1.0.</p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse distinctio modi reprehenderit impedit facere, ea hic a corporis recusandae unde minus commodi ducimus accusantium maiores ratione magnam dignissimos eos? Vero. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Enim sapiente doloremque ratione, dolor cupiditate recusandae inventore, impedit, iusto distinctio expedita odio maxime a aspernatur in voluptate dignissimos laboriosam! Voluptatem, corrupti. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Velit ipsam perspiciatis delectus dicta architecto, assumenda cumque, eaque quis omnis cum quia repellendus minima a maiores itaque accusamus ut odio eius?
    </section>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="cz-cs">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/application.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <title>Evidence</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div  id="content">
    <%= render 'home/header' %>
    <%= yield %>
    </div>
  <footer>
    <small>Vytvořila &copy; Marcela Pecková 2023</small>
  </footer>
  </body>
  
</html>

app/views/pojistenecs/_form.html.erb
<%= form_with(model: pojistenec) do |form| %>
  <% if pojistenec.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pojistenec.errors.count, "error") %> prohibited this pojistenec from being saved:</h2>

      <ul>
        <% pojistenec.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :"Jméno", style: "display: block" %>
    <%= form.text_field :jmeno %>
  </div>

  <div>
    <%= form.label :"Příjmení", style: "display: block" %>
    <%= form.text_field :prijmeni %>
  </div>

  <div>
    <%= form.label :"Datum narození", style: "display: block" %>
    <%= form.date_field :datum_narozeni %>
  </div>

  <div>
    <%= form.label :"Telefon", style: "display: block" %>
    <%= form.text_field :telefon %>
  </div>

  <div>
    <%= form.label :"E-mail", style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :"Ulice + čp.", style: "display: block" %>
    <%= form.text_area :ulice %>
  </div>

  <div>
    <%= form.label :"Město + psč", style: "display: block" %>
    <%= form.text_area :mesto %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pojistenecs/_pojistenec.html.erb
<header>

  <h1>Pojištěnec <%= pojistenec.jmeno %> <%= pojistenec.prijmeni %></h1>

</header>

<section>

  <div id="box">

    <%= link_to "Upravit", edit_pojistenec_path(pojistenec), class:"button", id:"zeleny" %>

    <%= button_to "Smazat", pojistenec, method: :delete, class:"button", id:"cerveny" %>

    <br>

  </div>

  <table id="info">

    <tr>

      <td>Datum narození</td>

      <td><%= pojistenec.datum_narozeni %></td>
    
    </tr>

    <tr>

      <td>Adresa:</td>

      <td><%= pojistenec.ulice %>, <%= pojistenec.mesto %></td>
      
    </tr>

    <tr>

      <td>Telefon:</td>

      <td><%= pojistenec.telefon %></td>

    </tr>

    <tr>

      <td>Email:</td>

      <td><%= pojistenec.email %></td>

    </tr>

  </table>
  
</section>

app/views/pojistenecs/edit.html.erb
<article>

  <h2>Úprava pojištěnce</h2>
  
  <%= render "form", pojistenec: @pojistenec %>
  
  <br>
  
  <div>

    <%= link_to "Otevřít záznam", @pojistenec, class:"button", id:"zeleny" %>
  
    <%= link_to "K pojistěncům", pojistenecs_path, class:"button", id:"zeleny" %>

  </div>

</article>

app/views/pojistenecs/index.html.erb
<article>

  <p style="color: green"><%= notice %></p>

  <header>
    <h1>Pojištěnci</h1>
    <div id="box">
      <%= link_to "Nový pojištěněc", new_pojistenec_path, class: "button", id:"zeleny" %>
    </div>
  </header>
  
  <section>

    <table>
      <thead>
        <th>ID</th>
        <th>Jméno</th>
        <th>Datum narození</th>
        <th>Adresa</th>
        <th>Akce</th>
      </thead>
      <tbody>
        <% @pojistenecs.each do |pojistenec| %>
        <tr>
          <td>
            <%= pojistenec.id %>
          </td>
          <td>
            <%= pojistenec.jmeno %> <%= pojistenec.prijmeni %>
          </td>
          <td>
            <%= pojistenec.datum_narozeni %>
          </td>
          <td>
            <%= pojistenec.ulice %>, <%= pojistenec.mesto%>
          </td>
          <td>
            <div id="box">
              <%= link_to "Zobrazit", pojistenec, class:"button", id:"zeleny" %> 
              <%= link_to "Upravit", edit_pojistenec_path(pojistenec), class:"button", id:"zeleny" %> 
              <%= button_to "Smazat", pojistenec, method: :delete, class:"button", id:"cerveny" %>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  
  </section>

</article>

app/views/pojistenecs/new.html.erb
<article>

  <h2>Nový pojištěnec</h2>  
  
  <%= render "form", pojistenec: @pojistenec %>
  
  <br>
  
  <div>

    <%= link_to "Zpět", pojistenecs_path, class:"button", id:"zeleny" %>

  </div>

</article>

app/views/pojistenecs/show.html.erb
<article>

  <p style="color: green"><%= notice %></p>
  
  <%= render @pojistenec %>
  
  <div id="box">
  
    <%= link_to "K pojistěncům", pojistenecs_path, class:"button", id:"zeleny" %>
  
  </div>

</article>

app/views/pojistenis/_form.html.erb
<%= form_with(model: pojisteni) do |form| %>
  <% if pojisteni.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pojisteni.errors.count, "error") %> prohibited this pojisteni from being saved:</h2>

      <ul>
        <% pojisteni.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :"Název", style: "display: block" %>
    <%= form.text_field :nazev %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pojistenis/_pojisteni.html.erb
<div id="<%= dom_id pojisteni %>">
  <p>
    <strong>Název:</strong>
    <%= pojisteni.nazev %>
  </p>

</div>

app/views/pojistenis/edit.html.erb
<article>
  
  <h1>Úprava pojištění</h1>

  <%= render "form", pojisteni: @pojisteni %>

  <br>

  <div>

    <%= link_to "K pojistěncům", pojistenecs_path, class:"button", id:"zeleny" %>

  </div>

</article>

app/views/pojistenis/index.html.erb
<article>

  <p style="color: green"><%= notice %></p>

  <header>
    <h1>Seznam pojištění</h1> 
    <div id="box">
      <%= link_to "Nové pojištění", new_pojisteni_path, class: "button", id:"zeleny" %>
    </div>
  </header>

  <section>
  
    <table>
      <thead>
        <th>id</th>
        <th>Název</th>
        <th>Akce</th>
      </thead>
      <tbody>
        <% @pojistenis.each do |pojisteni| %>
        <tr>
          <td>
            <%= pojisteni.id %>
          </td>
          <td>
            <%= pojisteni.nazev %>
          </td>
          <td>
            <div id="box">
              <%= link_to "Upravit", edit_pojisteni_path(pojisteni), class:"button", id:"zeleny" %> 
              <%= button_to "Smazat", pojisteni, method: :delete, class:"button", id:"cerveny" %>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </section>

</article>

app/views/pojistenis/new.html.erb
<article>

  <h1>Nové pojištění</h1>

  <%= render "form", pojisteni: @pojisteni %>

  <br>

  <div>
    <%= link_to "Zpět k seznamu pojištění", pojistenis_path, class:"button", id:"zeleny" %>
  </div>

</article>

app/views/pojistenis/show.html.erb
<article>
  
  <p style="color: green"><%= notice %></p>

  <%= render @pojisteni %>

  <div id="box">
    <%= link_to "Upravit", edit_pojisteni_path(@pojisteni), class:"button", id:"zeleny" %>
    <%= link_to "Zpět k seznamu pojištění", pojistenis_path, class:"button", id:"zeleny" %>
    <%= button_to "Odstranit", @pojisteni, method: :delete, class:"button", id:"cerveny" %>
  </div>

</article>